import { NextProvider } from "./providers";
import "./globals.css";
import LoginButton from "@/components/LoginButton";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <NextProvider>
          <header className="bg-gray-50">
            <div className="flex justify-between mx-2 text-3xl">
              <h1 className="my-2 font-bold">Reminder</h1>
              <LoginButton />
            </div>
            <nav className="px-2 py-2 space-x-2 text-2xl text-gray-700">
              <span>Search</span>
              <span>Setting</span>
            </nav>
            <hr />
          </header>
          {children}
        </NextProvider>
      </body>
    </html>
  );
}
