import { NextAuthProvider } from "./providers";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <header>
          <div>
            <h1>Reminder</h1>
            <div>user Area</div>
          </div>
          <nav>
            <span>test1</span>
            <span>test2</span>
            <span>test3</span>
          </nav>
        </header>
        <NextAuthProvider>{children}</NextAuthProvider>
      </body>
    </html>
  );
}
