import { NextAuthProvider } from "./providers";
import "./globals.css";
import LoginButton from "@/components/LoginButton";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <NextAuthProvider>
          <header>
            <div className="flex justify-between text-3xl mx-2">
              <h1 className=" my-2">Reminder</h1>
              <LoginButton />
            </div>
            <nav className="space-x-2 text-2xl mx-2">
              <span>test1</span>
              <span>test2</span>
              <span>test3</span>
            </nav>
          </header>
          {children}
        </NextAuthProvider>
      </body>
    </html>
  );
}
